### ISSUE TITLE
Use Go 1.13 errors

### ISSUE THREAD

**Issue by mikeraimondi** [mikeraimondi/gurnel#22]
Go 1.13 introduced an enhanced `errors` package. Gurnel should use the new enhancements.

Blog post on enhancements: https://peter.bourgon.org/blog/2019/09/11/programming-with-errors.html

Another (official) post: https://blog.golang.org/go1.13-errors

**Comment by sowmiyamuthuraman** [comment]
can i work on this?

**Comment by mikeraimondi** [comment]
@sowmiyamuthuraman absolutely!
